# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "18ae87dfbe26e41f27d47ede1f692961"
name = "DelayGuard"
handle = "delayguard-dev"
application_url = "https://delay-guard-6-production.up.railway.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_fulfillments,write_fulfillments,read_customers"

[auth]
redirect_urls = [
  "https://delay-guard-6-production.up.railway.app/auth/callback",
  "https://delay-guard-6-production.up.railway.app/auth/shopify/callback",
  "https://delay-guard-6-production.up.railway.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["fulfillments/create"]
uri = "/webhooks/fulfillments/create"

[[webhooks.subscriptions]]
topics = ["fulfillments/update"]
uri = "/webhooks/fulfillments/update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-store-1100000000000000000000000000000003980.myshopify.com"
